// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCooSwI0VCwDKwyd-Y5Ql4qqYUpfN_CrM',
    appId: '1:349086708062:web:73957b8a9387ce937b9fcf',
    messagingSenderId: '349086708062',
    projectId: 'instagram-71d86',
    authDomain: 'instagram-71d86.firebaseapp.com',
    storageBucket: 'instagram-71d86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfSki9vlvar6sQdRbey8T-VyITe7a3OQ',
    appId: '1:349086708062:android:daa4e76dde3caa967b9fcf',
    messagingSenderId: '349086708062',
    projectId: 'instagram-71d86',
    storageBucket: 'instagram-71d86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5l0Erc3c6udtOof992kJzhxRr9vqaNQ',
    appId: '1:349086708062:ios:3fbaa30f10e8e9c97b9fcf',
    messagingSenderId: '349086708062',
    projectId: 'instagram-71d86',
    storageBucket: 'instagram-71d86.appspot.com',
    iosClientId: '349086708062-obb54clqvuvj28p5m09a519khgaa2n8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5l0Erc3c6udtOof992kJzhxRr9vqaNQ',
    appId: '1:349086708062:ios:75c6ab92d73f024a7b9fcf',
    messagingSenderId: '349086708062',
    projectId: 'instagram-71d86',
    storageBucket: 'instagram-71d86.appspot.com',
    iosClientId: '349086708062-4s330rao8egp84tvbtp670hf51reftrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
